name: CI_Java_Project

on:
 workflow_dispatch:
  inputs:
   DESTINATION_ENV:
    type: environment
    default: staging

jobs:
  CI_Non_container_Build:
   runs-on: ubuntu-latest
   environment: ${{ inputs.DESTINATION_ENV }}
   steps:
#First, we have to checkout the code to Actions Repository from our github repo
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with: 
       java-version: 17
       distribution: microsoft
    - name: Get current date
      id: date
      run: echo "MY_DATE=$(date +%Y-%m-%d-%H-%M)" >> $GITHUB_ENV
    - name: Build using Maven
      run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
       name: artifact-${{ env.MY_DATE }}
       path: staging
    - run: echo 'Environment Secret is ${{secrets.secret}}, Environment Variable is ${{ vars.variable }}
